use_frameworks!

platform :ios, '9.0'

target 'STMessageAlertView_Example' do
  pod 'STMessageAlertView', :path => '../'

  target 'STMessageAlertView_Tests' do
    inherit! :search_paths

    
  end
end
