use_frameworks!

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'https://github.com/adolph-suntao/PrivateSpec.git' # 私有库Repo地址

target 'STMessageAlertView_Example' do
  pod 'STMessageAlertView', :path => '../'

  target 'STMessageAlertView_Tests' do
    inherit! :search_paths

    
  end
end
